# -*- coding: utf-8 -*-
"""assignment_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16ef-Y_Ydhk0uE03frV0-5OVLvcwGVt73

File -> data can be saved here as in a storage
Different modes in file:-
1. read(r) -> only allows to read the contents, no changes
2. write(w) -> changes can be made but previous data will be excluded
3. append(a) -> changes can be made including the previous data

We have created a file file1.txt and written 'Hi' there in 1st line
"""

#opening a file
myfile = open("file1.txt","r")
print(myfile)

#printing the contents of file using read() function
print(myfile.read())

#Whenever the file is not in use, we need to close the file
myfile.close()
print(myfile.read())

#write() function to make changes in file
myfile = open("file1.txt",'w')
myfile.write("This is from user")#gives length of string

myfile = open("file1.txt","r")
print(myfile.read())

myfile = open("file1.txt","a")
myfile.write("Hello all")

myfile = open("file1.txt","r")
print(myfile.read())

"""Another file is created named "file2.txt" and it contains a line "hello"
"""

mylines = [' good evening\n','welcome\n','Thanks\n']
#context manager -> automatically closes a file when not in use and prevents lagging
#using with keyword to close file automatically
with open("file2.txt","a") as myfile:
  myfile.writelines(mylines)
#the file is closed here 
with open("file2.txt","r") as myfile:
  print(myfile.read())
#the file is closed here

"""creating another file named "file3.txt"
"""

# r+ mode -> means reading and writing the file
with open("file3.txt","r+") as myfile:
  myfile.write("Hey there\n")
  myfile.seek(0)#bringing the cursor at the beginning
  print(myfile.read())

# w+ mode -> means reading and writing the file
with open("file3.txt","w+") as myfile:
  myfile.write("good evening\n")
  myfile.write("goodbye\n")
  myfile.seek(0)#bringing the cursor at the beginning
  print(myfile.read())# the previous data gets replaced

# a+ mode -> means reading and writing file, append mode
with open("file3.txt","a+") as f:
  f.write("hi again")
  f.seek(0)#bringing the cursor at the beginning
  print(f.read())#the previous data is not replaced