# -*- coding: utf-8 -*-
"""assignment_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pLyrBSHiBAwSi2--STi1Pe83JK_BLuM-

The 4 collection of data types are:
1. List
2. Tuple
3. Dictionary
4. Set

1. List
"""

# List -> ordered collection of datatypes,[],mutable
#Creating a list
list1=[123,34.21,'India',True]
print(list1[1])
print(list1)

#index() function
print(list1.index(True))

#len() function
print(len(list1))

#append() function
list1.append('hello')
print(list1)

#extend() function
list2 = [12,False]
list1.extend(list2)
print(list1)

#insert() function
list1.insert(2,'here')
print(list1)

#del keyword
del list1[1]
print(list1)

#remove() function
list1.remove('hello')
print(list1)

#deleting the list
del list1
print(list1)

"""2. Tuple"""

#Tuple -> ordered collection of datatypes,(),immutable
#Creating a tuple
tuple1 = (123,52.21,True,'hero')
print(tuple1[0])
print(tuple1)

#update
tuple1[4] = 65
print(tuple1)

#append() function
tuple1.append(12)
print(tuple1)

#insert() function
tuple1.insert(1,'hello')
print(tuple1)

#remove() function
tuple1.remove(True)
print(tuple1)

#len() function
print(len(tuple1))

#del keyword 
del tuple1
print(tuple1)

"""3. Dictionary"""

#Dictionary -> ordered key pair(key and value),{},mutable
#Creating a dictionary
dict1 = {
    'name':'Rahul',
    'class':10,
    'roll':2
}
print(dict1['class'])
print(dict1)

#update
dict1['name']='Rohan'
print(dict1)

#update() function
dict1.update({'name':'Sam'})
print(dict1)

#adding elements
dict1['section']='A'
print(dict1)
dict1['place']='Kolkata','India'
print(dict1)
list1 = ['bus','car']
dict1['Transport']=list1
print(dict1)

#update() function to add elements
dict1.update({'Title':'Das'})
print(dict1)

#del keyword
del dict1['roll']
print(dict1)

#merging using update() function
dict2 = {'a':10}
dict3 = {'b':20}
dict2.update(dict3)
print(dict2)

"""4. Set"""

# set -> unordered collection of datatypes,{},doesn't contain any duplicate values,mutable
# creating a set
myset = {"data","task",2,334.25,True,2}
print(myset)# randomly prints data, so indexing is not valid

#adding elements using add() function
myset.add(False)
print(myset)

#frozen set -> a set which doesn't get updated
myfrozenset = frozenset(["dell","hp"])#list inside a tuple
print(myfrozenset)

#adding elements in frozenset is not possible
myfrozenset.add('asus')
print(myfrozenset)

#union of sets using union() function
set1 = {1,23,4,56,4}
set2 = {2,"data",32,325,4,5647}
set3 = set1.union(set2)
print(set3)

#alternate method
set3 = set1|set2
print(set3)

#intersection of sets using intersection() method
set4 = set1.intersection(set2)
print(set4)

#alternate method
set4 = set1&set2
print(set4)

#find uncommons using difference() function
set5 = set1.difference(set2)
print(set5)